"""empty message

Revision ID: 1a42b4bd1e86
Revises: e3b4ab5bdaca
Create Date: 2022-06-15 19:26:39.886685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a42b4bd1e86'
down_revision = 'e3b4ab5bdaca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poketeam',
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.pokemon_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('poke_team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poke_team',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('poke_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['poke_id'], ['pokemon.pokemon_id'], name='poke_team_poke_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='poke_team_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='poke_team_pkey')
    )
    op.drop_table('poketeam')
    # ### end Alembic commands ###
